apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: argocd
  namespace: argocd
spec:
  interval: 5m
  releaseName: argocd
  chart:
    spec:
      chart: argo-cd
      version: "5.53.12" # Use latest stable
      sourceRef:
        kind: HelmRepository
        name: argo
        namespace: flux-system
  values:
    server:
      service:
        type: LoadBalancer
