apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: argo-workflows
  namespace: argo
spec:
  interval: 5m
  releaseName: argo-workflows
  chart:
    spec:
      chart: argo-workflows
      version: "0.40.15" # Use latest stable
      sourceRef:
        kind: HelmRepository
        name: argo
        namespace: flux-system
  values:
    server:
      serviceType: LoadBalancer
